#include "board.h"

#include "Task/z_main.h"
#include "Task/can_callbacks.h"
#include "freertos_vars.h"

#include "main.h"
#include "adc.h"
#include "can.h"
#include "dma.h"
#include "i2c.h"
#include "iwdg.h"
#include "spi.h"
#include "tim.h"
#include "usart.h"
#include "gpio.h"

extern "C" void SystemClock_Config(void);

void system_init() {
    HAL_Init();
    SystemClock_Config();
}

bool board_init() {
    // Initialize all configured peripherals
    MX_GPIO_Init();
    MX_DMA_Init();
    MX_ADC1_Init();
    MX_ADC2_Init();
    MX_ADC3_Init();
    MX_CAN1_Init();
    MX_CAN2_Init();
    MX_I2C1_Init();
    MX_I2C2_Init();
    MX_SPI1_Init();
    MX_SPI2_Init();  // Initialize SPI2 for BMI088
    MX_UART5_Init();
    MX_USART1_UART_Init();
    MX_USART2_UART_Init();
    MX_USART3_UART_Init();
    MX_USART6_UART_Init();
    MX_TIM2_Init();
    MX_UART4_Init();
    MX_IWDG_Init();
    MX_TIM1_Init();
    MX_TIM13_Init();

    // Initialize ZCAN for CAN1 and CAN2
    if (!can1_bus.start(&hcan1)) {
        return false;
    }
    if (!can2_bus.start(&hcan2)) {
        return false;
    }
    
    // Subscribe to dual optical flow CAN frames on CAN1.
    MsgIdFilterSpecs optflow_left_filter;
    optflow_left_filter.id = (uint16_t)kOptFlowCanIdLeft;
    optflow_left_filter.mask = 0x7FF;
    optflow_left_filter.fifo = CAN_RX_FIFO0;
    can1_bus.subscribe(optflow_left_filter, on_optflow_rx, nullptr, nullptr);

    MsgIdFilterSpecs optflow_right_filter;
    optflow_right_filter.id = (uint16_t)kOptFlowCanIdRight;
    optflow_right_filter.mask = 0x7FF;
    optflow_right_filter.fifo = CAN_RX_FIFO0;
    can1_bus.subscribe(optflow_right_filter, on_optflow_rx, nullptr, nullptr);
    
    // // Subscribe to motor feedback (CAN2, IDs 0x201-0x205)
    // for (uint16_t motor_id = 0x201; motor_id <= 0x205; motor_id++) {
    //     MsgIdFilterSpecs motor_filter;
    //     motor_filter.id = motor_id;
    //     motor_filter.mask = 0x7FF;
    //     motor_filter.fifo = CAN_RX_FIFO1;
    //     can2_bus.subscribe(motor_filter, on_motor_fb_rx, nullptr, nullptr);
    // }

    // NOTE: IMU data now comes from BMI088 via SPI2, not UART4
    // HAL_UARTEx_ReceiveToIdle_DMA(&huart4, robot.imu_rx_data, IMU_RX_DATA_LENGTH);

    // Start TIM2 for 1kHz control loop
    HAL_TIM_Base_Start_IT(&htim2);

    // Start TIM13 for optical flow sensor timing
    HAL_TIM_Base_Start(&htim13);

    return true;
}

extern "C" {

// FIXME: This function is auto-generated by STM32CubeMX in main.c.
// Comment it out there to avoid redefinition errors.
void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim) {
    if (htim->Instance == TIM14)
    {
        HAL_IncTick();
    }

    if (htim->Instance == TIM2) {
        // Release semaphore to wake CrtlTask (1kHz)
        osSemaphoreRelease(sem_ctrl_triggerHandle);
    }
}

// CAN RX FIFO0 callback for CAN1 (optical flow)
void HAL_CAN_RxFifo0MsgPendingCallback(CAN_HandleTypeDef *hcan) {
    if (hcan->Instance == CAN1) {
        can1_bus.process_rx_fifo(CAN_RX_FIFO0);
    }
}

// CAN RX FIFO1 callback for CAN2 (motors)
void HAL_CAN_RxFifo1MsgPendingCallback(CAN_HandleTypeDef *hcan) {
    if (hcan->Instance == CAN2) {
        can2_bus.process_rx_fifo(CAN_RX_FIFO1);
    }
}

void HAL_SPI_TxRxCpltCallback(SPI_HandleTypeDef *hspi)
{
}

void HAL_SPI_ErrorCallback(SPI_HandleTypeDef *hspi)
{
    if (__HAL_SPI_GET_FLAG(hspi, SPI_FLAG_MODF))
    {
        __HAL_SPI_CLEAR_MODFFLAG(hspi);
        __HAL_RCC_SPI1_FORCE_RESET();
        __HAL_RCC_SPI1_RELEASE_RESET();
        MX_SPI1_Init();
        // HAL_SPI_TransmitReceive_IT(hspi, robot.spiTxData, robot.spiRxData, spi_length);
    }
}

void HAL_UARTEx_RxEventCallback(UART_HandleTypeDef *huart, uint16_t Size)
{
    if (huart->Instance == USART1) {
        
    }

    if (huart->Instance == UART4) {
        /* read DR to clear RXNE; don't create an unused variable */
        (void)huart->Instance->DR;

        HAL_UARTEx_ReceiveToIdle_DMA(&huart4, robot.imu_rx_data, IMU_RX_DATA_LENGTH);
    }
}

} // extern "C"

